### ISSUE TITLE
model-qa.py is broken

### ISSUE THREAD

**Issue by theshaneobrien** [microsoft/onnxruntime-genai#1024]
**Describe the bug**
Since the addition of logit soft capping in https://github.com/microsoft/onnxruntime-genai/pull/876 model-qa.py is broken with the following error message:

```
(oga) PS C:\src\onnxruntime-genai> python .\examples\python\model-qa.py --verbose -m .\examples\python\builtAgain\
Loading model...
Traceback (most recent call last):
  File "C:\src\onnxruntime-genai\examples\python\model-qa.py", line 97, in <module>
    main(args)
  File "C:\src\onnxruntime-genai\examples\python\model-qa.py", line 11, in main
    model = og.Model(f'{args.model}')
            ^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime_genai.onnxruntime_genai.OrtException: Load model from .\examples\python\builtAgain\\model.onnx failed:This is an invalid model. In Node, ("/model/layers.0/attn/GroupQueryAttention", GroupQueryAttention, "com.microsoft", -1) : ("/model/layers.0/attn/qkv_proj/MatMulNBits/output_0": tensor(float),"","","past_key_values.0.key": tensor(float),"past_key_values.0.value": tensor(float),"/model/attn_mask_reformat/attn_mask_subgraph/Sub/Cast/output_0": tensor(int32),"/model/attn_mask_reformat/attn_mask_subgraph/Gather/Cast/output_0": tensor(int32),"cos_cache": tensor(float),"sin_cache": tensor(float),) -> ("/model/layers.0/attn/GroupQueryAttention/output_0": tensor(float),"present.0.key": tensor(float),"present.0.value": tensor(float),) , Error Unrecognized attribute: softcap for operator GroupQueryAttention
``` 

**To Reproduce**
1. Build a model with the current main builder.py
```
python .\src\python\py\models\builder.py -i ..\models\Llama-3.2-1B\ -o examples\python\builtAgain -p int4 -e cpu --extra_options int4_accuracy_level=3
``` 
2. Attempt to run said model with examples/python/model-qa.py4
```
python .\examples\python\model-qa.py -m .\examples\python\builtAgain\
```
3. . See error

**Expected behavior**
model-qa should just work or throw an error not related to expecting the softcap attribute

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: N/A
 - Current onnxruntime-genai main branch
 - python 3.12.7
 - pip packages
 - 
``` 
certifi            2024.8.30
charset-normalizer 3.4.0
colorama           0.4.6
coloredlogs        15.0.1
filelock           3.16.1
flatbuffers        24.3.25
fsspec             2024.10.0
huggingface-hub    0.26.2
humanfriendly      10.0
idna               3.10
Jinja2             3.1.4
MarkupSafe         3.0.2
mpmath             1.3.0
networkx           3.4.2
numpy              2.1.2
onnx               1.17.0
onnxruntime        1.19.2
onnxruntime-genai  0.4.0
packaging          24.1
pillow             11.0.0
pip                24.3.1
protobuf           5.28.3
pyreadline3        3.5.4
PyYAML             6.0.2
regex              2024.9.11
requests           2.32.3
safetensors        0.4.5
setuptools         75.3.0
sympy              1.13.1
tokenizers         0.20.1
torch              2.5.1
torchaudio         2.5.1
torchvision        0.20.1
tqdm               4.66.6
transformers       4.46.1
typing_extensions  4.12.2
urllib3            2.2.3
wheel              0.44.0
```

**Additional context**

**Comment by kunal-vaishnavi** [comment]
ONNX Runtime v1.20.0 has been released today. You can upgrade your ONNX Runtime version to fix this.
