### ISSUE TITLE
benchmark_e2e run time error

### ISSUE THREAD

**Issue by r-devulap** [microsoft/onnxruntime-genai#323]
Could someone help me fix this error? It looks like it runs fine on Windows, but on linux I get an error. 

```
>> python benchmark_e2e.py -i ../../../models/phi2-int4-cpu -b 1 -l 128 -g 5 -r 100 -w 10 -k 5 -o temp.csv -v
Loading model...
Model loaded
Traceback (most recent call last):
  File "/onnx/onnxruntime-genai/benchmark/python/benchmark_e2e.py", line 203, in <module>
    main(args)
  File "/onnx/onnxruntime-genai/benchmark/python/benchmark_e2e.py", line 66, in main
    prompt = [generate_prompt(model, tokenizer, prompt_length)] * batch_size
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/onnx/onnxruntime-genai/benchmark/python/benchmark_e2e.py", line 21, in generate_prompt
    params.set_search_options(do_sample=True, top_k=5, temperature=temperature, max_length=prompt_length, min_length=prompt_length+1)
TypeError: set_search_options(): incompatible function arguments. The following argument types are supported:
    1. (self: onnxruntime_genai.onnxruntime_genai.GeneratorParams, arg0: dict) -> None

Invoked with: <onnxruntime_genai.onnxruntime_genai.GeneratorParams object at 0x7f67619b8ab0>; kwargs: do_sample=True, top_k=5, temperature=1.0, max_length=128, min_length=
```

**Comment by baijumeswani** [comment]
[r-devulap](https://github.com/r-devulap) what version of the library are you using on linux?

Can you do a `pip list | grep onnxruntime-genai`?

**Comment by r-devulap** [comment]
```
>> pip list | grep onnxruntime-genai
onnxruntime-genai 0.1.0

```

**Comment by baijumeswani** [comment]
Could you please try to use the pre-release version?

`pip install --pre onnxruntime-genai`. You should get version 0.2.0-rc3 as of this now.

**Comment by r-devulap** [comment]
That worked! thank you :)

**Comment by sam-india-007** [comment]
Hi @baijumeswani I am having a similar issue on onnxruntime-genai-directml, even when using the pre-release version, could you check what's going wrong
