### ISSUE TITLE
Failing to load the GPU enabled model on Linux: `Protobuf parsing failed`

### ISSUE THREAD

**Issue by Ben-Epstein** [microsoft/onnxruntime-genai#376]
Code to reproduce:

```py
import onnxruntime_genai as og

chat_template = '<|user|>\n{input} <|end|>\n<|assistant|>'
model_name = "Phi-3-mini-128k-instruct-onnx/cuda/cuda-fp16"
model = og.Model(model_name)
generator = og.Generator(model, params)
```

Exception
```py
---------------------------------------------------------------------------
OrtException                              Traceback (most recent call last)
Cell In[1], line 5
      3 chat_template = '<|user|>\n{input} <|end|>\n<|assistant|>'
      4 model_name = "Phi-3-mini-128k-instruct-onnx/cuda/cuda-fp16"
----> 5 model = og.Model(model_name)
      6 generator = og.Generator(model, params)

OrtException: Load model from Phi-3-mini-128k-instruct-onnx/cuda/cuda-fp16/phi3-mini-128k-instruct-cuda-fp16.onnx failed:Protobuf parsing failed.
```

same issue with `Phi-3-mini-128k-instruct-onnx/cuda/cuda-int4-rtn-block-32/phi3-mini-128k-instruct-cuda-int4-rtn-block-32`

Thanks!

**Comment by Ben-Epstein** [comment]
Same thing if I run through the CLI 
```py
python phi3-qa.py -m Phi-3-mini-128k-instruct-onnx/cuda/cuda-fp16 -l 2048
Traceback (most recent call last):
  File "phi3-qa.py", line 87, in <module>
    main(args)
  File "phi3-qa.py", line 11, in main
    model = og.Model(f'{args.model}')
onnxruntime_genai.onnxruntime_genai.OrtException: Load model from Phi-3-mini-128k-instruct-onnx/cuda/cuda-fp16/phi3-mini-128k-instruct-cuda-fp16.onnx failed:Protobuf parsing failed.
```

**Comment by Ben-Epstein** [comment]
I also get the same issue actually with the CPU models

**Comment by Ben-Epstein** [comment]
Ah, the issue is that the lfs files weren't actually downloading. Ill update the instructions
