### ISSUE TITLE
cant install on aarch64 Raspbian64 Bullseye

### ISSUE THREAD

**Issue by zoldaten** [microsoft/onnxruntime-genai#567]
hi !
tried to install with `pip install onnxruntime-genai` - no candidate.
I have to build new cmake and put g++ version 10 (not 11) to CMakeList.txt.

I started building from source - https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/genai/howto/build-from-source.md

On step `./build.sh  --skip_tests --config Release` i got traceback with fail:
```
[ 79%] Building CXX object CMakeFiles/onnxruntime-genai.dir/src/generators.cpp.o
[ 79%] Building CXX object CMakeFiles/onnxruntime-genai.dir/src/json.cpp.o
/home/pi/onnxruntime-genai/src/json.cpp: In member function ‘double JSON::JSON::Parse_Number()’:
/home/pi/onnxruntime-genai/src/json.cpp:206:54: error: no matching function for call to ‘from_chars(const char*&, const char*&, double&)’
  206 |   auto result = std::from_chars(current_, end_, value);
      |                                                      ^
In file included from /home/pi/onnxruntime-genai/src/json.cpp:5:
/usr/include/c++/10/charconv:595:5: note: candidate: ‘template<class _Tp> std::__detail::__integer_from_chars_result_type<_Tp> std::from_chars(const char*, const char*, _Tp&, int)’
  595 |     from_chars(const char* __first, const char* __last, _Tp& __value,
      |     ^~~~~~~~~~
/usr/include/c++/10/charconv:595:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/10/bits/move.h:57,
                 from /usr/include/c++/10/bits/stl_pair.h:59,
                 from /usr/include/c++/10/utility:70,
                 from /usr/include/c++/10/algorithm:60,
                 from /home/pi/onnxruntime-genai/src/generators.h:6,
                 from /home/pi/onnxruntime-genai/src/json.cpp:1:
/usr/include/c++/10/type_traits: In substitution of ‘template<bool _Cond, class _Tp> using enable_if_t = typename std::enable_if::type [with bool _Cond = false; _Tp = std::from_chars_result]’:
/usr/include/c++/10/charconv:584:11:   required by substitution of ‘template<class _Tp> using __integer_from_chars_result_type = std::enable_if_t<std::__or_<std::__or_<std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, signed char>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, short int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long long int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, __int128> >, std::__or_<std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, unsigned char>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, short unsigned int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, unsigned int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long unsigned int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long long unsigned int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, __int128 unsigned> >, std::is_same<char, typename std::remove_cv< <template-parameter-1-1> >::type> >::value, std::from_chars_result> [with _Tp = double]’
/usr/include/c++/10/charconv:595:5:   required by substitution of ‘template<class _Tp> std::__detail::__integer_from_chars_result_type<_Tp> std::from_chars(const char*, const char*, _Tp&, int) [with _Tp = double]’
/home/pi/onnxruntime-genai/src/json.cpp:206:54:   required from here
/usr/include/c++/10/type_traits:2554:11: error: no type named ‘type’ in ‘struct std::enable_if<false, std::from_chars_result>’
 2554 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~
gmake[2]: *** [CMakeFiles/onnxruntime-genai.dir/build.make:118: CMakeFiles/onnxruntime-genai.dir/src/json.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1034: CMakeFiles/onnxruntime-genai.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/pi/onnxruntime-genai/build.py", line 469, in <module>
    build(arguments, environment)
  File "/home/pi/onnxruntime-genai/build.py", line 421, in build
    util.run(make_command, env=env)
  File "/home/pi/onnxruntime-genai/tools/python/util/run.py", line 56, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/pi/onnxruntime-genai/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
```

could you help a bit i almost there ? )

**Comment by baijumeswani** [comment]
Could you try enforcing USE_CXX17 here https://github.com/microsoft/onnxruntime-genai/blob/a6bec83bf02667f6a9c6aa6340842f46e001578c/cmake/cxx_standard.cmake#L2 and see if that helps?

**Comment by zoldaten** [comment]
that was an g++ issue. after install g++ 12 everything works!

not as fast as i expected - https://youtu.be/OsN2GwMwjQY
but works.

**Comment by skyline75489** [comment]
We should probably mention that G++ should be >= 11 somewhere in the doc. @zoldaten Thanks for trying it out!

**Comment by baijumeswani** [comment]
Happy to see that the compilation worked out. But sad to see the performance on the pi.

We can probably investigate into what can be done to speed-up the computation on the raspberrypi. @yufenglee for awareness.

I'll close this issue now.

**Comment by yufenglee** [comment]
@zoldaten, what CPU does your device have, cotex-a72? we only has optimization for arm v8.2 and above. cotext-a72 is v8.0.

**Comment by zoldaten** [comment]
> @zoldaten, what CPU does your device have, cotex-a72? we only has optimization for arm v8.2 and above. cotext-a72 is v8.0.

Cortex-A72 (ARM v8).
got it.

actually i tested phi3 https://youtu.be/3-TR5eG427M   and it was faster.
just thought it could be much more.
