### ISSUE TITLE
UnicodeDecodeError when try to run Phi-3-vision

### ISSUE THREAD

**Issue by yg1988** [microsoft/onnxruntime-genai#656]
Hi when trying to run Phi-3-vision, I got this error. Has anyone seen this before?

Loading model...
Traceback (most recent call last):
  File "D:\phi3-vision\Phi-3-vision-128k-instruct-onnx-cuda\phi3v.py", line 64, in <module>
    run(args)
  File "D:\phi3-vision\Phi-3-vision-128k-instruct-onnx-cuda\phi3v.py", line 14, in run
    model = og.Model(args.model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 233: invalid continuation byte

**Comment by yg1988** [comment]
It turns out I didn't download the full HF model files. This is not an issue with onnxruntime-genai sorry.
