### ISSUE TITLE
CodeQwen running error

### ISSUE THREAD

**Issue by aspi632** [microsoft/onnxruntime-genai#805]
**Describe the bug**
Hello guys, much appreciate your work here.
I have some problems with running a CodeQwen model. There is no errors in converting script and the onnx models appears in the output folder. However when I am trying to launch the `model-generate.py` it throwns an Error without any really helpfull information in a traceback.
I've tried both release version and build from source, the outcome is the same.
Will appreciate any suggestions on how to debug this error properly.

**To Reproduce**
1. Download official CodeQwen 1.5 weights from [HF](https://huggingface.co/Qwen/CodeQwen1.5-7B)
2. `python3 onnxruntime-genai/src/python/py/models/builder.py -i models/CodeQwen1.5-7B -o models/CodeQwen1.5-7B-onnx -p fp32 -e cpu` (using the `python3 -m onnxruntime_genai.models.builder` makes no difference)
3. Run the test `python3 onnxruntime-genai/examples/python/model-generate.py -m models/CodeQwen1.5-7B-onnx -pr "# Binary search on Python" -l 64` throws an IndexError with this traceback:
```
Prompt #0: # Binary search on Python

Traceback (most recent call last):
  File "/home/***/onnxruntime-genai/examples/python/model-generate.py", line 75, in <module>
    main(args)
  File "/home/***/onnxruntime-genai/examples/python/model-generate.py", line 51, in main
    print(tokenizer.decode(output_tokens[i]))
IndexError: map::at
```

**Desktop:**
 - OS: Ubuntu 22.04

**Additional context**
Please note that using the very same commands in the same environment I was able to convert the `codegemma-1.1-2b` to the onnx format and run the test. The response was accurate (correct binary search implementation) and without any errors at all. So I am expecting there is nothing wrong with my environment.

**Comment by aspi632** [comment]
Seems to be something with the tokenizer - I am trying a few other models for code generation using the same environment and command lines:
1. CodeLlama from [here](https://huggingface.co/codellama/CodeLlama-7b-hf)
2. `python3 onnxruntime-genai/src/python/py/models/builder.py -i models/CodeLlama-7b-hf -o models/CodeLlama-7b-hf-onnx -p fp32 -e cpu`
3. `python3 onnxruntime-genai/examples/python/model-generate.py -m models/CodeLlama-7b-hf-onnx -pr "# Binary search on Python" -l 64`

no errors here but the generation looks like this:
```
# Binary search on Python3.0<0x0A><0x0A><0x0A><0x0A><0x0A><0x0A>... (this token repeats endlessly)
```
also nothing changes if I play with the temperature or repetition penalty parameters

I have installed sentencepiece 0.2.0 and tiktoken 0.7.0 in my env if that makes any sense

**Comment by aspi632** [comment]
Just wanted to note that after 0.4.0 release situation is still the same with CodeQwen (and CodeLLama now behave the same)
The models.builder doesn't throws any error, the onnx conversion ends with these lines:
```
Saving GenAI config in /home/***/CodeLlama-7b-onnx-new
Saving processing files in /home/***/CodeLlama-7b-onnx-new for GenAI
```

However inference still fails with the same `IndexError: map::at` traceback for both models.
**@baijumeswani** can you help me with that?

**Comment by natke** [comment]
Thank you for the update. We are looking into the issue
