### ISSUE TITLE
using onnxruntime_genai.models.builder can't convert Phi-3.5-mini-instruct to int4-cpu

### ISSUE THREAD

**Issue by MaxAkbar** [microsoft/onnxruntime-genai#881]
**Describe the bug**
I am attempting to convert the Phi-3.5-mini-instruct to int4-cpu using the following instructions on [Quantizing Phi-3.5 using Generative AI extensions for onnxruntime](https://github.com/microsoft/Phi-3CookBook/blob/main/md/08.Update/Phi35/022.UsingORTGenAIQuantifyingPhi35.md)

**To Reproduce**
1. Download the [Phi-3.5-mini-instruct](https://huggingface.co/microsoft/Phi-3.5-mini-instruct)
2. Install libraries: `pip install torch transformers onnx onnxruntime`
3. And then install `pip install --pre onnxruntime-genai`
4. Finally run the following command: `python3 -m onnxruntime_genai.models.builder -m microsoft/Phi-3.5-mini-instruct  -o ./onnx-cpu -p int4 -e cpu -c ./Phi-3.5-mini-instruct`
5. See error 
```python -m onnxruntime_genai.models.builder -m microsoft/Phi-3.5-mini-instruct -o ./onnx-cpu-int4 -p int4 -e cpu -c ./Phi-3.5-mini-instruct
Valid precision + execution provider combinations are: FP32 CPU, FP32 CUDA, FP16 CUDA, FP16 DML, INT4 CPU, INT4 CUDA, INT4 DML
Extra options: {}
C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\configuration_auto.py:957: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
GroupQueryAttention (GQA) is used in this model.
C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\auto_factory.py:469: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
2024-09-06 17:48:17,759 transformers_modules.Phi-3.5-mini-instruct.modeling_phi3 [WARNING] - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
2024-09-06 17:48:17,760 transformers_modules.Phi-3.5-mini-instruct.modeling_phi3 [WARNING] - Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.66s/it]
Reading embedding layer
Reading decoder layer 0
Reading decoder layer 1
Reading decoder layer 2
Reading decoder layer 3
Reading decoder layer 4
Reading decoder layer 5
Reading decoder layer 6
Reading decoder layer 7
Reading decoder layer 8
Reading decoder layer 9
Reading decoder layer 10
Reading decoder layer 11
Reading decoder layer 12
Reading decoder layer 13
Reading decoder layer 14
Reading decoder layer 15
Reading decoder layer 16
Reading decoder layer 17
Reading decoder layer 18
Reading decoder layer 19
Reading decoder layer 20
Reading decoder layer 21
Reading decoder layer 22
Reading decoder layer 23
Reading decoder layer 24
Reading decoder layer 25
Reading decoder layer 26
Reading decoder layer 27
Reading decoder layer 28
Reading decoder layer 29
Reading decoder layer 30
Reading decoder layer 31
Reading final norm
Reading LM head
Saving ONNX model in ./onnx-cpu-int4
2024-09-06 17:50:09,495 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.0/attn/qkv_proj/MatMul ...
2024-09-06 17:50:09,636 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.0/attn/qkv_proj/MatMul ...
2024-09-06 17:50:09,644 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.0/attn/o_proj/MatMul ...
2024-09-06 17:50:09,701 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.0/attn/o_proj/MatMul ...
2024-09-06 17:50:09,704 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.0/mlp/gate_proj/MatMul ...
2024-09-06 17:50:09,862 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.0/mlp/gate_proj/MatMul ...
2024-09-06 17:50:09,868 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.0/mlp/up_proj/MatMul ...
2024-09-06 17:50:09,967 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.0/mlp/up_proj/MatMul ...
2024-09-06 17:50:09,971 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.0/mlp/down_proj/MatMul ...
2024-09-06 17:50:10,054 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.0/mlp/down_proj/MatMul ...
2024-09-06 17:50:10,059 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.1/attn/qkv_proj/MatMul ...
2024-09-06 17:50:10,142 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.1/attn/qkv_proj/MatMul ...
2024-09-06 17:50:10,147 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.1/attn/o_proj/MatMul ...
2024-09-06 17:50:10,181 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.1/attn/o_proj/MatMul ...
2024-09-06 17:50:10,183 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.1/mlp/gate_proj/MatMul ...
2024-09-06 17:50:10,279 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.1/mlp/gate_proj/MatMul ...
2024-09-06 17:50:10,285 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.1/mlp/up_proj/MatMul ...
2024-09-06 17:50:10,392 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.1/mlp/up_proj/MatMul ...
2024-09-06 17:50:10,396 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.1/mlp/down_proj/MatMul ...
2024-09-06 17:50:10,491 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.1/mlp/down_proj/MatMul ...
2024-09-06 17:50:10,496 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.2/attn/qkv_proj/MatMul ...
2024-09-06 17:50:10,597 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.2/attn/qkv_proj/MatMul ...
2024-09-06 17:50:10,602 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.2/attn/o_proj/MatMul ...
2024-09-06 17:50:10,640 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.2/attn/o_proj/MatMul ...
2024-09-06 17:50:10,642 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.2/mlp/gate_proj/MatMul ...
2024-09-06 17:50:10,747 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.2/mlp/gate_proj/MatMul ...
2024-09-06 17:50:10,753 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.2/mlp/up_proj/MatMul ...
2024-09-06 17:50:10,841 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.2/mlp/up_proj/MatMul ...
2024-09-06 17:50:10,845 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.2/mlp/down_proj/MatMul ...
2024-09-06 17:50:10,924 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.2/mlp/down_proj/MatMul ...
2024-09-06 17:50:10,928 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.3/attn/qkv_proj/MatMul ...
2024-09-06 17:50:11,013 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.3/attn/qkv_proj/MatMul ...
2024-09-06 17:50:11,018 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.3/attn/o_proj/MatMul ...
2024-09-06 17:50:11,051 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.3/attn/o_proj/MatMul ...
2024-09-06 17:50:11,053 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.3/mlp/gate_proj/MatMul ...
2024-09-06 17:50:11,143 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.3/mlp/gate_proj/MatMul ...
2024-09-06 17:50:11,147 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.3/mlp/up_proj/MatMul ...
2024-09-06 17:50:11,234 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.3/mlp/up_proj/MatMul ...
2024-09-06 17:50:11,238 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.3/mlp/down_proj/MatMul ...
2024-09-06 17:50:11,316 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.3/mlp/down_proj/MatMul ...
2024-09-06 17:50:11,320 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.4/attn/qkv_proj/MatMul ...
2024-09-06 17:50:11,405 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.4/attn/qkv_proj/MatMul ...
2024-09-06 17:50:11,409 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.4/attn/o_proj/MatMul ...
2024-09-06 17:50:11,439 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.4/attn/o_proj/MatMul ...
2024-09-06 17:50:11,441 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.4/mlp/gate_proj/MatMul ...
2024-09-06 17:50:11,552 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.4/mlp/gate_proj/MatMul ...
2024-09-06 17:50:11,561 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.4/mlp/up_proj/MatMul ...
2024-09-06 17:50:11,720 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.4/mlp/up_proj/MatMul ...
2024-09-06 17:50:11,727 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.4/mlp/down_proj/MatMul ...
2024-09-06 17:50:11,853 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.4/mlp/down_proj/MatMul ...
2024-09-06 17:50:11,857 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.5/attn/qkv_proj/MatMul ...
2024-09-06 17:50:11,936 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.5/attn/qkv_proj/MatMul ...
2024-09-06 17:50:11,941 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.5/attn/o_proj/MatMul ...
2024-09-06 17:50:11,971 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.5/attn/o_proj/MatMul ...
2024-09-06 17:50:11,973 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.5/mlp/gate_proj/MatMul ...
2024-09-06 17:50:12,064 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.5/mlp/gate_proj/MatMul ...
2024-09-06 17:50:12,069 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.5/mlp/up_proj/MatMul ...
2024-09-06 17:50:12,153 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.5/mlp/up_proj/MatMul ...
2024-09-06 17:50:12,157 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.5/mlp/down_proj/MatMul ...
2024-09-06 17:50:12,233 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.5/mlp/down_proj/MatMul ...
2024-09-06 17:50:12,238 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.6/attn/qkv_proj/MatMul ...
2024-09-06 17:50:12,327 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.6/attn/qkv_proj/MatMul ...
2024-09-06 17:50:12,332 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.6/attn/o_proj/MatMul ...
2024-09-06 17:50:12,361 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.6/attn/o_proj/MatMul ...
2024-09-06 17:50:12,363 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.6/mlp/gate_proj/MatMul ...
2024-09-06 17:50:12,444 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.6/mlp/gate_proj/MatMul ...
2024-09-06 17:50:12,449 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.6/mlp/up_proj/MatMul ...
2024-09-06 17:50:12,556 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.6/mlp/up_proj/MatMul ...
2024-09-06 17:50:12,562 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.6/mlp/down_proj/MatMul ...
2024-09-06 17:50:12,673 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.6/mlp/down_proj/MatMul ...
2024-09-06 17:50:12,677 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.7/attn/qkv_proj/MatMul ...
2024-09-06 17:50:12,763 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.7/attn/qkv_proj/MatMul ...
2024-09-06 17:50:12,768 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.7/attn/o_proj/MatMul ...
2024-09-06 17:50:12,796 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.7/attn/o_proj/MatMul ...
2024-09-06 17:50:12,798 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.7/mlp/gate_proj/MatMul ...
2024-09-06 17:50:12,883 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.7/mlp/gate_proj/MatMul ...
2024-09-06 17:50:12,887 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.7/mlp/up_proj/MatMul ...
2024-09-06 17:50:12,975 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.7/mlp/up_proj/MatMul ...
2024-09-06 17:50:12,979 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.7/mlp/down_proj/MatMul ...
2024-09-06 17:50:13,054 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.7/mlp/down_proj/MatMul ...
2024-09-06 17:50:13,061 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.8/attn/qkv_proj/MatMul ...
2024-09-06 17:50:13,142 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.8/attn/qkv_proj/MatMul ...
2024-09-06 17:50:13,147 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.8/attn/o_proj/MatMul ...
2024-09-06 17:50:13,176 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.8/attn/o_proj/MatMul ...
2024-09-06 17:50:13,179 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.8/mlp/gate_proj/MatMul ...
2024-09-06 17:50:13,269 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.8/mlp/gate_proj/MatMul ...
2024-09-06 17:50:13,273 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.8/mlp/up_proj/MatMul ...
2024-09-06 17:50:13,363 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.8/mlp/up_proj/MatMul ...
2024-09-06 17:50:13,368 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.8/mlp/down_proj/MatMul ...
2024-09-06 17:50:13,443 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - complete quantization of /model/layers.8/mlp/down_proj/MatMul ...
2024-09-06 17:50:13,447 onnxruntime.quantization.matmul_4bits_quantizer [INFO] - start to quantize /model/layers.9/attn/qkv_proj/MatMul ...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime_genai\models\builder.py", line 2615, in <module>
    create_model(args.model_name, args.input, args.output, args.precision, args.execution_provider, args.cache_dir, **extra_options)
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime_genai\models\builder.py", line 2511, in create_model
    onnx_model.save_model(output_dir)
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime_genai\models\builder.py", line 379, in save_model
    model = self.to_int4(model)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime_genai\models\builder.py", line 409, in to_int4
    quant.process()
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\quantization\matmul_4bits_quantizer.py", line 729, in process
    self._process_subgraph(graph_stack)
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\quantization\matmul_4bits_quantizer.py", line 642, in _process_subgraph
    out_nodes = self.node_quantizer.quantize(node, graph_stack)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\quantization\matmul_4bits_quantizer.py", line 504, in quantize
    b_graph.initializer.extend([b_quant, scales_tensor])
google.protobuf.message.DecodeError: Error parsing message
```

**Expected behavior**
I get the model converted into onnx format:

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Edge]
 - Version [10.0.26120 Build 26120]

**Smartphone (please complete the following information):**
N/A

**Additional context**
I am able to convert to:
1. Fp16-cuda
2. Fp32-cuda
3. Cpu-fp16

I can then use the sample code in https://github.com/microsoft/onnxruntime-genai/tree/main/examples/csharp/Genny to run the models without issues.

**Comment by kunal-vaishnavi** [comment]
> pip install torch transformers onnx onnxruntime
> OS: [Windows 11]

There is [a Windows issue](https://github.com/onnx/onnx/pull/6342) with the latest `protobuf` version that is downloaded when installing `onnx`. You will need to downgrade your `protobuf` version to 5.27 or lower.

> pip install --pre onnxruntime-genai

The `pip install --pre onnxruntime-genai` command will install a pre-release version. A stable version of ONNX Runtime GenAI has now been released and you can upgrade to it.

Here's how you can change these package versions.

```bash
# Uninstall `protobuf`, `onnxruntime`, and `onnxruntime-genai`
$ pip uninstall -y onnxruntime onnxruntime-genai protobuf

# Install `protobuf` with a version less than 5.28
$ pip install protobuf==5.27

# Install stable release of `onnxruntime-genai`, which will install `onnxruntime` as well for you
# Starting with this stable release of ONNX Runtime GenAI, ONNX Runtime will also be installed for you.
# Please read here for more details on why the dependency has been added: https://onnxruntime.ai/docs/genai/howto/install.html#onnx-runtime-dependency
$ pip install onnxruntime-genai
```

**Comment by kunal-vaishnavi** [comment]
> pip install torch transformers onnx onnxruntime
> OS: [Windows 11]

There is [a Windows issue](https://github.com/onnx/onnx/pull/6342) with the latest `protobuf` version that is downloaded when installing `onnx`. You will need to downgrade your `protobuf` version to 5.27 or lower.

> pip install --pre onnxruntime-genai

The `pip install --pre onnxruntime-genai` command will install a pre-release version. A stable version of ONNX Runtime GenAI has now been released and you can upgrade to it.

Here's how you can change these package versions.

```bash
# Uninstall `protobuf`, `onnxruntime`, and `onnxruntime-genai`
$ pip uninstall -y protobuf onnxruntime onnxruntime-genai

# Install `protobuf` with a version less than 5.28
$ pip install protobuf==5.27

# Install stable release of `onnxruntime-genai`, which will install `onnxruntime` as well for you
# Starting with this stable release of ONNX Runtime GenAI, ONNX Runtime will also be installed for you.
# Please read here for more details on why the dependency has been added: https://onnxruntime.ai/docs/genai/howto/install.html#onnx-runtime-dependency
$ pip install onnxruntime-genai
```

**Comment by MaxAkbar** [comment]
Thank you @kunal-vaishnavi, I have tried every variation of the protobuf and either it hangs or errors out. No matter what I do it won't convert the model to onnx cpu int4.

Here is my current versions: 
```
PS C:\Users\****\source\repos\models> pip show protobuf
Name: protobuf
Version: 5.27.0
Summary:
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires:
Required-by: google-api-core, googleapis-common-protos, onnx, onnxruntime, onnxruntime-gpu
PS C:\Users\****\source\repos\models> pip show onnxruntime
Name: onnxruntime
Version: 1.19.2
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by: onnxruntime-genai
PS C:\Users\****\source\repos\models> pip show onnxruntime-genai
Name: onnxruntime-genai
Version: 0.4.0
Summary: ONNX Runtime generate() API
Home-page:
Author: Microsoft Corporation
Author-email: onnxruntime-genai@microsoft.com
License: MIT License
Location: C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: numpy, onnxruntime
Required-by:
PS C:\Users\****\source\repos\models>
```

**Comment by kunal-vaishnavi** [comment]
Couple of questions:

1. Can you share the full list of packages installed in your environment?
2. What is printed when it hangs? It is possible that you are running out of memory during quantization.
3. Is the above traceback the only one seen when it errors out? If not, can you share other tracebacks you have seen along with the package versions installed during those attempts?
4. What is the traceback you see with your current versions installed (`protobuf = 5.27.0`, `onnxruntime = 1.19.2`, `onnxruntime-genai = 0.4.0`)? Is is the same traceback as the above one?
5. Can you downgrade `protobuf` to `3.20.2` and try again? On PyPI, [the `requires_dist` section](https://pypi.org/pypi/onnx/1.16.2/json) for the latest ONNX release shows that `v3.20.2` is the minimum `protobuf` version required.

**Comment by MaxAkbar** [comment]
Hi @kunal-vaishnavi, downgrading `protobuf` to `3.20.2` worked, thank you. Yay!
