### ISSUE TITLE
Mac build from source not working: onnx .dylib link [Mac M3/ARM/MACOS]

### ISSUE THREAD

**Issue by farris** [microsoft/onnxruntime-genai#909]
**Describe the bug**
When following the steps to build the generate() API from source [link](https://onnxruntime.ai/docs/genai/howto/build-from-source.html), there is an issue linking the API back to the onnxruntime dependency 

```bash
Traceback (most recent call last):
  File "onnxruntime-genai/examples/python/phi3-qa.py", line 1, in <module>
    import onnxruntime_genai as og
  File "/.venvs/universal_venv/lib/python3.12/site-packages/onnxruntime_genai/__init__.py", line 9, in <module>
    _dll_directory.add_onnxruntime_dependency(__id__)
  File "/.venvs/universal_venv/lib/python3.12/site-packages/onnxruntime_genai/_dll_directory.py", line 62, in add_onnxruntime_dependency
    raise ImportError("Could not find the onnxruntime shared library.")
ImportError: Could not find the onnxruntime shared library.
```

**Expected behavior**
To fix it, I changed the _dll_directory script to point to the onnx dylib 
```python
target_lib_path = "~/Desktop/dev/onnxruntime-genai/ort/lib/libonnxruntime.dylib"
```

**Additional context**
Do with this info what you will 😄

**Comment by skyline75489** [comment]
Hi @farris, the current version of GenAI doesn't have full support on macOS. I'm working on improving this and it should be improved in the next release. Thanks for trying it out :)

**Comment by skyline75489** [comment]
This should've been fixed and `onnxruntime-genai` can be installed through pip on macOS now.
