### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'detach' while converting neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16

### ISSUE THREAD

**Issue by csetanmayjain** [microsoft/onnxruntime-genai#953]
I'm attempting to convert the quantized model [Meta-Llama-3.1-8B-Instruct-quantized.w4a16](https://huggingface.co/neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16) to ONNX using the ONNXRuntime GenAI library.

**Steps to reproduce**:

1. Download the model locally: (Since, quantized doesn't support -m https://github.com/microsoft/onnxruntime-genai/issues/771
   ```bash
   huggingface-cli download neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16
   ```

2. Run the following command:
   ```bash
   python3 -m onnxruntime_genai.models.builder -i "Meta-Llama-3.1-8B-Instruct-quantized.w4a16" -o "quant.onnx" -p 'int4' -e 'cuda' -c cache_dir_to_store_temp_files
   ```

The process throws the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/users/tanmay_jain/codes/py3_venv/lib/python3.8/site-packages/onnxruntime_genai/models/builder.py", line 2615, in <module>
    create_model(args.model_name, args.input, args.output, args.precision, args.execution_provider, args.cache_dir, **extra_options)
  File "/mnt/users/tanmay_jain/codes/py3_venv/lib/python3.8/site-packages/onnxruntime_genai/models/builder.py", line 2508, in create_model
    onnx_model.make_model(input_path)
  File "/mnt/users/tanmay_jain/codes/py3_venv/lib/python3.8/site-packages/onnxruntime_genai/models/builder.py", line 1625, in make_model
    self.make_embedding(module.weight.detach().numpy())
AttributeError: 'NoneType' object has no attribute 'detach'
```

**Environment**:
- Python version: 3.8
- Model: [Meta-Llama-3.1-8B-Instruct-quantized.w4a16](https://huggingface.co/neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16)

**Comment by kunal-vaishnavi** [comment]
Here's how I obtained the PyTorch model from Hugging Face.
```
$ sudo apt-get install git-lfs
$ git clone https://huggingface.co/neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16
```

Then I was able to get the ONNX model without any issues by using ONNX Runtime GenAI v0.4.0 and Transformers v4.44.0.

```
$ git clone https://github.com/microsoft/onnxruntime-genai
$ cd onnxruntime-genai/src/python/py/models/
$ python3 -m onnxruntime_genai.models.builder -i /path/to/Meta-Llama-3.1-8B-Instruct-quantized.w4a16/ -o ./output_dir -p int4 -e cuda -c /path/to/cache_dir/
Valid precision + execution provider combinations are: FP32 CPU, FP32 CUDA, FP16 CUDA, FP16 DML, INT4 CPU, INT4 CUDA, INT4 DML
Extra options: {}
/path/to/transformers/src/transformers/models/auto/configuration_auto.py:957: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
GroupQueryAttention (GQA) is used in this model.
Unpacking and repacking layer 0
Unpacking and repacking layer 1
Unpacking and repacking layer 2
Unpacking and repacking layer 3
Unpacking and repacking layer 4
Unpacking and repacking layer 5
Unpacking and repacking layer 6
Unpacking and repacking layer 7
Unpacking and repacking layer 8
Unpacking and repacking layer 9
Unpacking and repacking layer 10
Unpacking and repacking layer 11
Unpacking and repacking layer 12
Unpacking and repacking layer 13
Unpacking and repacking layer 14
Unpacking and repacking layer 15
Unpacking and repacking layer 16
Unpacking and repacking layer 17
Unpacking and repacking layer 18
Unpacking and repacking layer 19
Unpacking and repacking layer 20
Unpacking and repacking layer 21
Unpacking and repacking layer 22
Unpacking and repacking layer 23
Unpacking and repacking layer 24
Unpacking and repacking layer 25
Unpacking and repacking layer 26
Unpacking and repacking layer 27
Unpacking and repacking layer 28
Unpacking and repacking layer 29
Unpacking and repacking layer 30
Unpacking and repacking layer 31
Reading embedding layer
Reading decoder layer 0
Reading decoder layer 1
Reading decoder layer 2
Reading decoder layer 3
Reading decoder layer 4
Reading decoder layer 5
Reading decoder layer 6
Reading decoder layer 7
Reading decoder layer 8
Reading decoder layer 9
Reading decoder layer 10
Reading decoder layer 11
Reading decoder layer 12
Reading decoder layer 13
Reading decoder layer 14
Reading decoder layer 15
Reading decoder layer 16
Reading decoder layer 17
Reading decoder layer 18
Reading decoder layer 19
Reading decoder layer 20
Reading decoder layer 21
Reading decoder layer 22
Reading decoder layer 23
Reading decoder layer 24
Reading decoder layer 25
Reading decoder layer 26
Reading decoder layer 27
Reading decoder layer 28
Reading decoder layer 29
Reading decoder layer 30
Reading decoder layer 31
Reading final norm
Reading LM head
Saving ONNX model in ./output_dir
/path/to/transformers/src/transformers/generation/configuration_utils.py:924: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Saving GenAI config in ./output_dir
/path/to/transformers/src/transformers/models/auto/tokenization_auto.py:785: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Saving processing files in ./output_dir for GenAI
```

Can you try again using the example command and these package versions?

**Comment by kunal-vaishnavi** [comment]
Here's how I obtained the PyTorch model from Hugging Face.
```
$ sudo apt-get install git-lfs
$ git clone https://huggingface.co/neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16
```

Then I was able to get the ONNX model without any issues by using ONNX Runtime GenAI v0.4.0 and Transformers v4.44.0.

```
$ python3 -m onnxruntime_genai.models.builder -i /path/to/Meta-Llama-3.1-8B-Instruct-quantized.w4a16/ -o ./output_dir -p int4 -e cuda -c /path/to/cache_dir/
Valid precision + execution provider combinations are: FP32 CPU, FP32 CUDA, FP16 CUDA, FP16 DML, INT4 CPU, INT4 CUDA, INT4 DML
Extra options: {}
/path/to/transformers/src/transformers/models/auto/configuration_auto.py:957: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
GroupQueryAttention (GQA) is used in this model.
Unpacking and repacking layer 0
Unpacking and repacking layer 1
Unpacking and repacking layer 2
Unpacking and repacking layer 3
Unpacking and repacking layer 4
Unpacking and repacking layer 5
Unpacking and repacking layer 6
Unpacking and repacking layer 7
Unpacking and repacking layer 8
Unpacking and repacking layer 9
Unpacking and repacking layer 10
Unpacking and repacking layer 11
Unpacking and repacking layer 12
Unpacking and repacking layer 13
Unpacking and repacking layer 14
Unpacking and repacking layer 15
Unpacking and repacking layer 16
Unpacking and repacking layer 17
Unpacking and repacking layer 18
Unpacking and repacking layer 19
Unpacking and repacking layer 20
Unpacking and repacking layer 21
Unpacking and repacking layer 22
Unpacking and repacking layer 23
Unpacking and repacking layer 24
Unpacking and repacking layer 25
Unpacking and repacking layer 26
Unpacking and repacking layer 27
Unpacking and repacking layer 28
Unpacking and repacking layer 29
Unpacking and repacking layer 30
Unpacking and repacking layer 31
Reading embedding layer
Reading decoder layer 0
Reading decoder layer 1
Reading decoder layer 2
Reading decoder layer 3
Reading decoder layer 4
Reading decoder layer 5
Reading decoder layer 6
Reading decoder layer 7
Reading decoder layer 8
Reading decoder layer 9
Reading decoder layer 10
Reading decoder layer 11
Reading decoder layer 12
Reading decoder layer 13
Reading decoder layer 14
Reading decoder layer 15
Reading decoder layer 16
Reading decoder layer 17
Reading decoder layer 18
Reading decoder layer 19
Reading decoder layer 20
Reading decoder layer 21
Reading decoder layer 22
Reading decoder layer 23
Reading decoder layer 24
Reading decoder layer 25
Reading decoder layer 26
Reading decoder layer 27
Reading decoder layer 28
Reading decoder layer 29
Reading decoder layer 30
Reading decoder layer 31
Reading final norm
Reading LM head
Saving ONNX model in ./output_dir
/path/to/transformers/src/transformers/generation/configuration_utils.py:924: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Saving GenAI config in ./output_dir
/path/to/transformers/src/transformers/models/auto/tokenization_auto.py:785: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Saving processing files in ./output_dir for GenAI
```

Can you try again using the example command and these package versions?

**Comment by csetanmayjain** [comment]
Thanks, it worked.
Seems the issue was because of the broken `git-lfs`
